#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# voice-transcriber macOS installer
#
# Run once:   ./install_mac.sh
# Then use:   voice-transcriber             (CLI mode — record and transcribe)
#             voice-transcriber --clipboard  (auto-copy result to clipboard)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_DIR="$PROJECT_DIR/.venv"
LOCAL_BIN="$HOME/.local/bin"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
fail()  { echo -e "${RED}[x]${NC} $*"; exit 1; }

# ── 1. Homebrew ──────────────────────────────────────────────────────────────

if ! command -v brew &>/dev/null; then
    fail "Homebrew is not installed. Install it first: https://brew.sh"
fi

info "Checking system dependencies (Homebrew)..."

brew_install() {
    if brew list "$1" &>/dev/null; then
        info "$1 already installed."
    else
        info "Installing $1..."
        brew install "$1"
    fi
}

brew_install portaudio
brew_install ffmpeg

# ── 2. Python ────────────────────────────────────────────────────────────────

# Use python3 from Homebrew or system (macOS ships Python 3.10+ on Ventura+)
PYTHON="$(command -v python3)"
PY_VERSION=$("$PYTHON" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
info "Using Python $PY_VERSION at $PYTHON"

if [[ "$PY_VERSION" < "3.10" ]]; then
    fail "Python 3.10 or newer is required. Install it with: brew install python"
fi

# ── 3. Python venv + packages ────────────────────────────────────────────────

if [ ! -d "$VENV_DIR" ]; then
    info "Creating Python virtual environment..."
    "$PYTHON" -m venv "$VENV_DIR"
fi

info "Installing Python packages (this may take a few minutes the first time)..."
if command -v uv &>/dev/null; then
    uv pip install --python "$VENV_DIR/bin/python" openai-whisper sounddevice numpy
else
    "$VENV_DIR/bin/python" -m ensurepip --upgrade 2>/dev/null || true
    "$VENV_DIR/bin/python" -m pip install --quiet openai-whisper sounddevice numpy
fi

# ── 4. Wrapper script in ~/.local/bin ────────────────────────────────────────

mkdir -p "$LOCAL_BIN"

info "Installing 'voice-transcriber' command to $LOCAL_BIN ..."

cat > "$LOCAL_BIN/voice-transcriber" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by install_mac.sh — do not edit manually
exec "$VENV_DIR/bin/python" "$PROJECT_DIR/transcriber.py" "\$@"
WRAPPER
chmod +x "$LOCAL_BIN/voice-transcriber"

# Ensure ~/.local/bin is on PATH (add to shell rc if missing)
for rc in "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile"; do
    if [ -f "$rc" ] && ! grep -q '/.local/bin' "$rc" 2>/dev/null; then
        echo '' >> "$rc"
        echo '# Added by voice-transcriber install_mac.sh' >> "$rc"
        echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$rc"
        info "Added ~/.local/bin to PATH in $rc"
        break
    fi
done

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
info "Installation complete!"
echo ""
echo "  Reload your shell first (or open a new terminal tab), then:"
echo ""
echo "    voice-transcriber              Record and transcribe to stdout"
echo "    voice-transcriber --clipboard  Transcribe and copy to clipboard"
echo "    voice-transcriber -m small     Use a more accurate Whisper model"
echo ""
echo "  Usage:"
echo "    1. Run: voice-transcriber --clipboard"
echo "    2. Speak into your microphone"
echo "    3. Press ENTER or SPACE to stop"
echo "    4. Result is printed AND in your clipboard — Cmd+V to paste"
echo ""
echo "  Tip: bind a hotkey to open a terminal and run:"
echo "    voice-transcriber --clipboard"
echo "  via macOS Shortcuts app or Alfred."
echo ""
